# Generated by Django 6.0.3 on 2026-03-17 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_mediafile_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediafile',
            name='category',
        ),
    ]
