# Generated by Django 6.0.3 on 2026-03-17 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='audio',
        ),
        migrations.RemoveField(
            model_name='song',
            name='image',
        ),
        migrations.RemoveField(
            model_name='song',
            name='title',
        ),
        migrations.AlterField(
            model_name='song',
            name='category',
            field=models.CharField(max_length=20),
        ),
    ]
