# Generated by Django 6.0.3 on 2026-03-18 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_remove_song_audio_remove_song_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='category',
            field=models.CharField(choices=[('love', 'Love Songs'), ('sad', 'Sad Songs'), ('motivation', 'Motivation Songs'), ('old', 'Old Songs')], max_length=20),
        ),
    ]
