# Generated by Django 6.0.3 on 2026-03-17 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images/')),
                ('category', models.CharField(choices=[('love', 'Love'), ('sad', 'Sad'), ('motivation', 'Motivation'), ('old', 'Old')], max_length=20)),
                ('audio', models.FileField(upload_to='audio/')),
            ],
        ),
    ]
